<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.jettra</groupId>
        <artifactId>JettraFileManager</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>jettra-receptor</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.jettra</groupId>
            <artifactId>JettraChunks</artifactId>
        </dependency>
        <dependency>
            <groupId>io.jettra</groupId>
            <artifactId>JettraGRPC</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jettra</groupId>
            <artifactId>JettraServer</artifactId>
        </dependency>
    </dependencies>
</project>
